- name: install rpm repository
  yum: name=https://dev.mysql.com/get/mysql57-community-release-el6-11.noarch.rpm state=present
- name: install mysqld
  yum: name={{ item }} disablerepo=mysql57-community enablerepo=mysql56-community state=present
  with_items:
    - mysql-community-server
    - mysql-community-client
    - mysql-community-common
    - mysql-community-libs
    - mysql-community-libs-compat
    - MySQL-python
    - libselinux-python
  tags: mysql

- name: mysql start
  service: name=mysqld state=started enabled=yes
  tags: mysql

- name: change root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
  tags: mysql

- name: /root/.my.cnf by template
  template:
    src: templates/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  tags: mysql

- name: add user
  mysql_user:
    name: "{{ mysql_user_name}}"
    password: "{{ mysql_user_password }}"
    host: localhost
    priv: '*.*:ALL,GRANT'
  tags: mysql

