- name: yum install epel-repease
  yum: name=epel-release state=installed
  tags: php7

- name: add remi-repo repository
  command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo
  tags: php7

- name: install php 7.1
  yum: name={{ item }} enablerepo=remi,remi-php71 state=installed
  with_items:
    - php
    - php-devel
    - php-fpm
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-pdo
    - php-xml
    - php-zip
  tags: php7
- name: deploy php.ini
  template:
    src: php.ini.j2
    dest: /etc/php.ini
  tags: php7